"""add-clone-url

Revision ID: 7d2d689baabf
Revises: be5babf9a162
Create Date: 2026-07-15 04:52:07.467568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d2d689baabf'
down_revision: Union[str, Sequence[str], None] = 'be5babf9a162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('clone_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'clone_url')
    # ### end Alembic commands ###
