"""fix repository index jobs

Revision ID: 89c23a7eb9d4
Revises: 294d7bafc432
Create Date: 2026-07-17 14:10:43.879013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89c23a7eb9d4'
down_revision: Union[str, Sequence[str], None] = '294d7bafc432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repository_index_jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_index_jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('repository_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('queued', 'cloning', 'scanning', 'chunking', 'embedding', 'completed', 'failed', 'cancelled', name='indexstatus'), autoincrement=False, nullable=False),
    sa.Column('total_files', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('processed_files', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_chunks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('processed_chunks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('repository_index_jobs_repository_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('repository_index_jobs_pkey'))
    )
    # ### end Alembic commands ###
