"""extend repository

Revision ID: a25ce9a32f22
Revises: e09245fdd8d1
Create Date: 2026-07-17 17:15:50.935116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a25ce9a32f22'
down_revision: Union[str, Sequence[str], None] = 'e09245fdd8d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('index_current_file', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('index_next_chunk', sa.Integer(), nullable=False))
    op.add_column('repository_files', sa.Column('indexed', sa.Boolean(), nullable=False))
    op.add_column('repository_files', sa.Column('last_indexed_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repository_files', 'last_indexed_hash')
    op.drop_column('repository_files', 'indexed')
    op.drop_column('repositories', 'index_next_chunk')
    op.drop_column('repositories', 'index_current_file')
    # ### end Alembic commands ###
