"""update

Revision ID: a508c6fb3e4a
Revises: b2bf610b91ba
Create Date: 2026-07-15 03:28:19.582023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a508c6fb3e4a'
down_revision: Union[str, Sequence[str], None] = 'b2bf610b91ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('last_synced_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'last_synced_at')
    # ### end Alembic commands ###
