"""extend repository

Revision ID: e09245fdd8d1
Revises: 89c23a7eb9d4
Create Date: 2026-07-17 14:35:15.788036

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e09245fdd8d1'
down_revision: Union[str, Sequence[str], None] = '89c23a7eb9d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('index_total_chunks', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('repositories', sa.Column('index_processed_chunks', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('repositories', sa.Column('index_total_batches', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('repositories', sa.Column('index_processed_batches', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('repositories', sa.Column('error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'error')
    op.drop_column('repositories', 'index_processed_batches')
    op.drop_column('repositories', 'index_total_batches')
    op.drop_column('repositories', 'index_processed_chunks')
    op.drop_column('repositories', 'index_total_chunks')
    # ### end Alembic commands ###
